<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html><head><title>
Home page</title>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script><script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<body>
<style type="text/css">#op-fo-ta{margin:auto;}#op-fo-ta .input{width:185px;padding:2px;}#op-fo-ta label{display:block;font-weight:normal;font-size:11px;padding:4px 5px 3px 5px;}</style><script type="text/javascript">function _reload(){$('#captcha').optoken({u:_url,t:'p',r:mt_rand(100,1000)});}$(function(){function request(){var user=$("#username"),pass=$("#password"),code=$("#code"),tip=$("tempnouse"),fields=$([]).add(user).add(pass).add(code);var bV = true;fields.removeClass('ui-state-error');if($("#username").val()!='root'){bV=bV&&_c_Length(tip,user,"username",5,16);bV=bV&&_c_Regexp(tip,user,/^([0-9a-z_])+$/i,"Username may consist of a-z A-Z 0-9, case sensitive and underscores.");}bV=bV&&_c_Length(tip,pass,"password",6,60);bV=bV&&_c_Length(tip,code,"verification Code",4,4);bV=bV&&_c_Regexp(tip,code,/^([A-Z])+$/,"Verification Code: field only allow : A-Z");if(!bV){return false}else{$.ajax({type:'POST',url:_url+'/?v=l&nocache=true',data:'type=login&user='+user.val()+'&password='+pass.val()+'&code='+code.val(),cache:false,success:function(html){if(html == 'success'){document.location.href=_url+'/?v=l&l0=0';}else{fields.val('');_reload();$.jGrowl(html,{header:"Important!",sticky:true});}}});}}o = $('#op-fo-ta');$('.input', o).addClass('ui-widget-content').val('');$('label, .tip', o).hover(function(){$(this).addClass('ui-state-hover')}, function(){$(this).removeClass('ui-state-hover')});$('.op-tip').each(function(){if($(this).html() == ''){$(this).html('<span class="ui-icon ui-icon-help"></span>')}});$('#captcha').optoken({u:_url,t:'p',r:mt_rand(100,1000)}).click(function(){_reload()});$('.request').click(function(){request();});$('input').bind('keypress',function(e){if(e.keyCode==13){request();}});});</script>

<style type="text/css">#op-fo-ta{margin:auto;}#op-fo-ta .input{width:185px;padding:2px;}#op-fo-ta label{display:block;font-weight:normal;font-size:11px;padding:4px 5px 3px 5px;}</style><script type="text/javascript">function _reload(){$('#captcha').optoken({u:_url,t:'p',r:mt_rand(100,1000)});}$(function(){function request(){var user=$("#username"),pass=$("#password"),code=$("#code"),tip=$("tempnouse"),fields=$([]).add(user).add(pass).add(code);var bV = true;fields.removeClass('ui-state-error');if($("#username").val()!='root'){bV=bV&&_c_Length(tip,user,"username",5,16);bV=bV&&_c_Regexp(tip,user,/^([0-9a-z_])+$/i,"Username may consist of a-z A-Z 0-9, case sensitive and underscores.");}bV=bV&&_c_Length(tip,pass,"password",6,60);bV=bV&&_c_Length(tip,code,"verification Code",4,4);bV=bV&&_c_Regexp(tip,code,/^([A-Z])+$/,"Verification Code: field only allow : A-Z");if(!bV){return false}else{$.ajax({type:'POST',url:_url+'/?v=l&nocache=true',data:'type=login&user='+user.val()+'&password='+pass.val()+'&code='+code.val(),cache:false,success:function(html){if(html == 'success'){document.location.href=_url+'/?v=l&l0=0';}else{fields.val('');_reload();$.jGrowl(html,{header:"Important!",sticky:true});}}});}}o = $('#op-fo-ta');$('.input', o).addClass('ui-widget-content').val('');$('label, .tip', o).hover(function(){$(this).addClass('ui-state-hover')}, function(){$(this).removeClass('ui-state-hover')});$('.op-tip').each(function(){if($(this).html() == ''){$(this).html('<span class="ui-icon ui-icon-help"></span>')}});$('#captcha').optoken({u:_url,t:'p',r:mt_rand(100,1000)}).click(function(){_reload()});$('.request').click(function(){request();});$('input').bind('keypress',function(e){if(e.keyCode==13){request();}});});</script>



